---
title: "Choose the Data"
author: "Amwaj Almalki"
date: "17/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse,WDI,Almalki)
```

## Series List

UIS.FEP.56.F900
:  Percentage of students enrolled in Health and Welfare programmes in tertiary education who are female (%)


## Download All Series

```{r}
outcome_indicators <-
  c(
    "5.51.01.03.mortal",
    "HF.DYN.MORT",
    "SH.DYN.MORT",
    "UIS.FEP.56.F900",
    'NY.ADJ.DMIN.GN.ZS',
    'NY.ADJ.DRES.GN.ZS',
    'NY.ADJ.DRES.GN.ZS',
    
    'EG.ELC.ACCS.ZS',
    'SE.PRM.TENR',
    'NY.ADJ.NNTY.KD.ZG',
    'NY.ADJ.NNTY.KD',
    'NY.ADJ.NNTY.PC.KD.ZG',
    'NY.ADJ.NNTY.PC.KD',
    'NY.ADJ.DKAP.GN.ZS',
    'SP.ADO.TFRT',
    'SP.POP.DPND',
    'FB.BNK.CAPA.ZS',
    'FB.AST.NPER.ZS',
    'SP.DYN.CBRT.IN',
    'FB.CBK.BRWR.P3',
    'FM.LBL.BMNY.CN',
    'SH.DTH.COMM.ZS',
    'SH.DTH.INJR.ZS',
    'SH.DTH.NCOM.ZS',
    'AG.PRD.CREL.MT',
    'GC.XPN.COMP.ZS',
    'FP.CPI.TOTL',
    'SH.XPD.CHEX.GD.ZS',
    'SP.DYN.CDRT.IN',
    'SH.XPD.GHED.GD.ZS',
    'SH.XPD.GHED.PC.CD',
    'EG.ELC.NGAS.ZS',
    'EG.ELC.NUCL.ZS',
    'SL.AGR.EMPL.ZS',
    'SL.IND.EMPL.ZS',
    'SL.SRV.EMPL.ZS',
    'SL.EMP.TOTL.SP.FE.NE.ZS',
    'SL.EMP.TOTL.SP.MA.ZS',
    'GC.XPN.TOTL.GD.ZS',
    'NE.CON.TOTL.KD',
    'EG.USE.COMM.FO.ZS',
    'NY.GDP.MKTP.KD',
    'NY.GDP.MKTP.KD.ZG',
    'NY.GDP.PCAP.KD',
    'NY.GNP.MKTP.KD',
    'SE.PRM.GINT.ZS',
    'SH.IMM.IDPT',
    'SH.IMM.HEPB',
    'SH.IMM.MEAS',
    'FP.CPI.TOTL.ZG',
    'ST.INT.XPND.CD',
    'SP.DYN.LE00.FE.IN',
    'SP.DYN.LE00.MA.IN',
    'SP.DYN.LE00.IN',
    'SH.MMR.RISK.ZS',
    'SH.MMR.RISK',
    'SH.STA.MMRT',
    'SH.STA.TRAF.P5',
    'SH.DYN.NCOM.ZS',
    'SH.DYN.NCOM.FE.ZS',
    'SH.DYN.NCOM.MA.ZS',
    'SP.DYN.AMRT.FE',
    'SP.DYN.AMRT.MA',
    'SP.DYN.IMRT.IN',
    'SP.DYN.IMRT.FE.IN',
    'SP.DYN.IMRT.MA.IN',
    'SH.DYN.MORT.FE',
    'SH.DYN.MORT.MA'
  ) 

```

```{r}
series_description <-
  map(outcome_indicators,
      function(.x) {
        WDIsearch(string = paste0("^", .x, "$"),
                  short = FALSE,
                  field = 'indicator')
      })

```

```{r}
names(series_description[[1]])
series_description[[1]][['name']]
```

```{r}
WDIsearch(string = paste0("^","HF.DYN.MORT","$"),
           field = 'indicator', short = FALSE)
```


```{r}
series_description[1]$`5.51.01.03.mortal`
series_description[3][[1]]
```

```{r}
extract_info <- function(.element){
  sapply(series_description,function(.x){
    .x[[.element]]
    }
    )
}
names(series_description[[1]])
extract_info('name')
```



```{r}
h <- WDI::WDI(indicator = outcome_indicators)
h %>% 
head()
```
```{r}
d <- h %>% 
  filter(year > 2000) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(x5_51_01_03_mortal),!is.na(hf_dyn_mort)) 
```



##  Save Data to Package
```{r}
data.table::fwrite(h,"data-raw/h.csv")
```
```{r}
data.table::fwrite(d,"data-raw/d.csv")
```


```{r}
usethis::use_data(h,overwrite = TRUE)
```
```{r}
usethis::use_data(d,overwrite = TRUE)
```



